name: Build luci-app-natpierce (all arch)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: '请输入要发布的版本号 (例: v1.0.0)'
        required: false
        default: ''
      text:
        description: '请输入发布说明'
        required: false
        default: ''

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  TAG: "${{ github.event.inputs.tag }}"

permissions:
  contents: write

jobs:
  build:
    name: Build all arch package sdk:${{ matrix.sdk }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64
        sdk:
          - 22.03.2
          - SNAPSHOT

    steps:
      - uses: actions/checkout@v4

      - name: Generate contributor list and avatars
        run: |
          chmod +x ./scripts/get_contributors.sh
          ./scripts/get_contributors.sh

      - name: Copy package to OpenWrt build directory
        run: |
          mkdir -p package/
          mv luci-app-natpierce package/

      - name: Building luci-app-natpierce
        uses: openwrt/gh-action-sdk@main
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.sdk }}
          PACKAGES: luci-app-natpierce
          V: s
      
      - name: Upload packages as artifact
        uses: actions/upload-artifact@v4
        with:
          name: luci-app-natpierce-all-${{ matrix.sdk }}
          path: bin/packages/${{ matrix.arch }}/action/
          if-no-files-found: warn

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.event.inputs.tag != '' }}

    steps:
      - name: Download all packages
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create release and upload files
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ github.event.inputs.tag }}
          body: |
            此版本包含 luci-app-natpierce 所有架构的 ipk 和 apk 包。
            ${{ github.event.inputs.text }}
          files: artifacts/**/*.ipk artifacts/**/*.apk